#Application name
spring.application.name=YMS-vmart

#Project port selection
server.port=8082

#db configuration:
#data source :
spring.datasource.url=jdbc:mysql://localhost:3306/VYMS?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Vijay
#spring.datasource.driver-class-name=com.mysql.jdbc.cj.Driver

#jpa or hibernate configurations
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.hibernate.ddl-auto=update